name: test
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: registry:latest
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: prepare
        run: chmod a+x ./gradlew
      - name: build
        run: ./gradlew :build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}